"""Independent exact-kernel and flux checks for a complete-support divergent path.

Run: python -B analysis/correctness/mechanism.py
The four-state rates below are explicit inputs, not generated by the orbit helper.
The general half-line statement follows analytically from continuity and divergence;
this example checks the mechanism and does not classify any whole entropy set.
"""
if not __debug__:
    raise SystemExit("Assertions must be enabled; do not use python -O or PYTHONOPTIMIZE.")

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import platform

import mpmath as mp
import sympy as sp

ROOT = Path(__file__).resolve().parents[2]


def main():
    e, lam = sp.symbols('e lambda', real=True)
    q = sp.Matrix([
        [-6, 1, 2*(1-e), 3+2*e],
        [2, -9, 3*(1-e), 4+3*e],
        [(4-6*e)/(1-e), 5, -15-4*e, (6-4*e**2)/(1-e)],
        [6, 5, 4*(1-e), -15+4*e]])
    base = q.subs(e, 0)
    assert (q*sp.ones(4,1)).applyfunc(sp.cancel) == sp.zeros(4,1)
    # On 0 <= e < 2/3, all twelve off-diagonals are positive. The only
    # limiting zero is h -> x; 6-4e^2 >= 38/9 and 1-e >= 1/3.
    endpoint = sp.Rational(2,3)
    limit = q.subs(e,endpoint)
    assert limit[2,0] == 0 and limit[0,2] == sp.Rational(2,3)
    assert all(limit[i,j] > 0 for i in range(4) for j in range(4)
               if i != j and (i,j) != (2,0))
    r = sp.Matrix([[0,1,0,0],[1,0,0,0]])
    b = sp.Matrix([[1,0],[0,2],[0,0],[0,0]])
    marked = sp.zeros(4); marked[0,1]=1; marked[1,0]=2
    transform = r*(lam*sp.eye(4)-(q-marked)).inv()*b
    transform0 = r*(lam*sp.eye(4)-(base-marked)).inv()*b
    assert (transform-transform0).applyfunc(sp.cancel) == sp.zeros(2)
    # Direct stationary solve at e=0, then verify a proposed law in the
    # explicitly supplied generator (no imported similarity implementation).
    a = base.T.copy(); a[3,:] = sp.ones(1,4)
    pi0 = a.inv()*sp.Matrix([0,0,0,1])
    pi = sp.Matrix([pi0[0],pi0[1],(1-e)*pi0[2],pi0[3]+e*pi0[2]])
    assert (pi.T*q).applyfunc(sp.cancel) == sp.zeros(1,4)
    assert sp.cancel(sum(pi)-1) == 0
    coeff = sp.cancel(pi0[0]*sp.Rational(2,3))
    assert coeff > 0
    # The flux pi_h q_hx vanishes linearly. Every other forward/reverse
    # flux has a positive finite limit, so sigma/log(1/(2/3-e)) -> coeff.
    vanishing = sp.cancel(pi[2]*q[2,0])
    assert sp.cancel(vanishing/(endpoint-e)) == 6*pi0[2]

    mp.mp.dps = 160
    def number(x):
        x=sp.Rational(x)
        return mp.mpf(int(x.p))/int(x.q)

    diagnostics=[]
    for exponent in (10,30,60):
        ep = endpoint-sp.Rational(1,10**exponent)
        qm = mp.matrix([[number(x) for x in row] for row in q.subs(e,ep).tolist()])
        system=qm.T.copy()
        for j in range(4): system[3,j]=1
        stationary=mp.lu_solve(system,mp.matrix([0,0,0,1]))
        entropy=mp.mpf('0')
        for i in range(4):
            for j in range(i+1,4):
                f,g=stationary[i]*qm[i,j],stationary[j]*qm[j,i]
                entropy += (f-g)*mp.log(f/g)
        diagnostics.append({'delta_power':exponent,'entropy':mp.nstr(entropy,100),
                            'entropy_over_log':mp.nstr(entropy/(exponent*mp.log(10)),100)})
    slope=(mp.mpf(diagnostics[-1]['entropy'])-mp.mpf(diagnostics[-2]['entropy']))/(30*mp.log(10))
    assert abs(slope-number(coeff)) < mp.mpf('1e-25')
    result={'time_utc':datetime.now(timezone.utc).isoformat(),
        'command':'python -B analysis/correctness/mechanism.py',
        'versions':{'python':platform.python_version(),'sympy':sp.__version__,'mpmath':mp.__version__},
        'source_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'inputs':{'explicit_generator':str(q),'parameter_domain':'0 <= e < 2/3',
                  'observed_marks':'x->y and y->x; known endpoints; full joint waiting kernels'},
        'exact_checks':{'row_normalization':True,'full_resolvent_equivalence':True,
                        'stationarity':True,'single_vanishing_reverse_flux':True},
        'stationary_base':[str(x) for x in pi0],
        'entropy_logarithmic_coefficient':str(coeff),
        'numeric_check':'Independent 160-digit stationary LU and edge flux entropy; no rate clipping.',
        'numeric_diagnostics':diagnostics,'seed':None,
        'scope':'Exact illustrative family plus flux-limit check, not exhaustive classification. General attainable half-line follows from the intermediate value theorem on the already proved divergent path.',
        'all_checks_passed':True}
    out=ROOT/'outputs/correctness-2026-09-15/mechanism.json'
    out.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
    print('Exact complete-support path and independent entropy limit passed; coefficient =',coeff)


if __name__ == '__main__':
    main()
